version: 2
jobs:
  build:
    docker:
      - image: node:11.12.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  test:
    docker:
      - image: node:11.12.0
    steps:
      - checkout
      - run: npm install
      - run: npm test:unit

  publish:
    docker:
      - image: node:11.12.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      # TODO: Publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
